server:
  port: 9200

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
