server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtGatewayFilter

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/departments/**
          filters:
            - JwtGatewayFilter

        - id: department-exists
          uri: lb://department-service
          predicates:
            - Path=/api/v1/departments/is-exist/**
          filters:
            - JwtGatewayFilter

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/auth/**

        - id: permission-service
          uri: lb://permission-service
          predicates:
            - Path=/api/v1/role-permission/**
          filters:
            - JwtGatewayFilter
